BAUD_RATE = 921600
HEADER_BYTES = (0xFF, 0xFF)
PAYLOAD_FLOATS = 10
PAYLOAD_SIZE = PAYLOAD_FLOATS * 4

BOARD_WIDTH_CM = 57.5
BOARD_LENGTH_CM = 42.5
WEIGHT_THRESHOLD_KG = 2.0
TARE_SAMPLE_COUNT = 100

LAYOUT_SIDE_BY_SIDE = "side_by_side"
LAYOUT_FRONT_BACK = "front_back"

READ_POLL_INTERVAL_S = 0.001
